### ISSUE TITLE
Use Process component instead of hardcoded exec

### ISSUE THREAD

**Issue by stloyd** [artur-gajewski/DocumentorBundle#2]
Why using hardcoded `exec()` in command instead of Symfony [Process](http://symfony.com/doc/current/components/process.html) Component ?

**Comment by artur-gajewski** [comment]
@stloyd: Indeed, I will make this change as soon as I get to, or perhaps you want to send me a PR?

**Comment by artur-gajewski** [comment]
Fixed it so it uses Process() instead of Exec() now. Thanks @stloyd !
